name: 29931_test

on:
  push:
    branches: [ "main" ]  # workflow se sproži ob pushu na main

jobs:

  preveri_test:
    runs-on: self-hosted  # uporablja tvoj lokalni runner (ne GitHub-hosted)

    outputs:
      napaka: ${{ steps.preveri.outputs.napaka }}  # posreduje rezultat v naslednji job

    steps:
      - uses: actions/checkout@v4  # potegne repo na runner

      - name: Preveri obstoj testov
        id: preveri
        run: |
          # preveri ali obstaja testna datoteka
          if [ ! -f test_main.py ]; then
            echo "TESTI MANJKAJO" > napaka.txt   # zapis napake v file
            echo "napaka=1" >> $GITHUB_OUTPUT    # signal za fail
          else
            echo "" > napaka.txt                 # prazna napaka = OK
            echo "napaka=0" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: napaka      # ime artefakta (kasneje ga downloadas)
          path: napaka.txt  # file, ki ga pošiljaš med jobi


  testiranje:
    needs: preveri_test  # ta job se izvede šele po prvem

    # pomembno: testiranje se izvede samo če ni napake
    if: needs.preveri_test.outputs.napaka == '0'

    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.9, 3.11]  # (več verzij testiranja)

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pip install -r requirements.txt
          pip install pytest
       
       -name: Izpis
          run: |
          echo "lalala"


      - name: Run tests
        run: |
          pytest test_main.py 2> napaka.txt  # stderr gre v file

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt